# Generated by Django 4.2.7 on 2023-12-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Enter post title', max_length=200, verbose_name='Title of the post')),
                ('body', models.TextField(help_text='Enter post text', verbose_name='Body of the post')),
                ('user', models.IntegerField(default=99999942, verbose_name='user')),
                ('is_synced', models.BooleanField(default=False, help_text='JSONPlaceholder syncronization status', verbose_name='Post syncronization status')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField(help_text='Enter comment text', verbose_name='Body of the comment')),
                ('is_synced', models.BooleanField(default=False, help_text='JSONPlaceholder syncronization status', verbose_name='Comment syncronization status')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='master_system.post')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('id',),
            },
        ),
    ]
