# Generated by Django 4.2.7 on 2023-12-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_system', '0002_remove_post_is_synced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_synced',
        ),
    ]
